### PR TITLE
Fix number input eager clamping on keystrokes

### LINKED ISSUE #581: [BUG] Number input clamps value on every keystroke, making it painful to type large values
### Duplicate check

- [x] I have searched for existing issues and confirmed this is not a duplicate.

### Before submitting a bug report, I have:

- [x] Reviewed the documentation.
- [x] Ensured I am using ghcr.io/cleanuparr/cleanuparr docker repository.
- [x] Ensured I am using the latest version.
- [x] Enabled verbose logging.

### What is the behavior?

When typing into any number input field, the value is clamped to the field's `min`/`max` range on every keystroke. This makes it very difficult to type values that start with a digit below the minimum.

**Steps to reproduce**
1. Open Queue Cleaner → Add/Edit a Stall Rule
2. Click into the Max Strikes field (min: 3, max: 5000)
3. Type a value starting with a digit below the minimum — e.g. `1000` (just over 3 days)

**Expected behavior**
The field shows `1000` as typed.

**Actual behavior**
Typing `1` immediately clamps to `3` (the minimum), so continuing produces `3000` instead of `1000`. Any value that *starts below the minimum* gets mangled on the very first keystroke.

I noticed this while setting up stall rules for the first time and trying to configure a round value like `1000` (just over 3 days). I eventually had to figure out the workaround of typing one less than my target and hitting `+`

**Suggested fix**
Move the min/max enforcement from the `input` event to the `blur` event. Free typing is allowed; clamping happens only when the user leaves the field:

```
onInput(event):
  if field is empty → set value to null, return
  set value = parse(field.value)   // no clamping — let them type

onBlur(event):
  clamp value to [min, max]
  update field display if value changed
  emit blur event
```

The existing inline error messages (e.g. "Min value is 3") already provide feedback during typing, so the user isn't left without guidance while mid-entry.

Happy to submit a PR if this approach looks good to you.

### Which operating system do you use?

MacOS

### What type of deployment do you use?

Docker container

### Relevant log output

_N/A — this is a pure UI bug with no relevant log output._

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by MikeTheCanuck**
## Description

Fixes eager min/max clamping in the `app-number-input` component that interrupted typing mid-keystroke. Previously, `onInput` called `Math.max`/`Math.min` on every keystroke, so typing `-1` would clamp to `0` after the `-`, and typing `1000` would clamp to the max after each digit.

The fix moves clamping to `onBlur`: the value is clamped and the DOM input synced only when the field loses focus, leaving the user free to type any intermediate value.

## Related Issue

Closes #581

## Type of Change

- [x] Bug fix
- [ ] New feature
- [ ] Breaking change
- [ ] Documentation update

## Testing

- Typed `-1` into Max Ratio, Max Seed Time, and Max Inactive Days fields — no mid-keystroke jumps
- Typed `1000` into a field with `[max]="999"` — value clamped correctly on blur
- Typed and then cleared a field — no errors, value resets to null as before

## Checklist

- [x] I have read the [Contributing Guide](../CONTRIBUTING.md)
- [x] I have announced my intent to work on this and received approval (issue #581)
- [x] My code follows the project's code standards
- [x] I have tested my changes thoroughly
- [ ] I have updated relevant documentation

### CODE REVIEW

File: code/frontend/src/app/ui/number-input/number-input.component.ts [hunk 1]
```diff
@@ -34,21 +34,23 @@ export class NumberInputComponent {
...
-    if (maxVal != null) {
-      num = Math.min(num, maxVal);
+  onBlur(event: FocusEvent): void {
+    const current = this.value();
+    if (current != null) {
+      let clamped = current;
+      const minVal = this.min();
+      const maxVal = this.max();
+      if (minVal != null) clamped = Math.max(clamped, minVal);
+      if (maxVal != null) clamped = Math.min(clamped, maxVal);
```
Comment (Flaminel) [inline code/frontend/src/app/ui/number-input/number-input.component.ts]: Add the braces back.

File: code/frontend/src/app/ui/number-input/number-input.component.ts [hunk 2]
```diff
@@ -34,21 +34,23 @@ export class NumberInputComponent {
...
+      if (clamped !== current) {
+        this.value.set(clamped);
+        (event.target as HTMLInputElement).value = String(clamped);
```
Comment (Flaminel) [inline code/frontend/src/app/ui/number-input/number-input.component.ts]: Why is this needed if we're already setting the value through `this.value.set(clamped)`?

File: code/frontend/src/app/ui/number-input/number-input.component.ts (hunk 1 above)
Comment (MikeTheCanuck) [reply code/frontend/src/app/ui/number-input/number-input.component.ts]: Done, braces added.

File: code/frontend/src/app/ui/number-input/number-input.component.ts (hunk 2 above)
Comment (MikeTheCanuck) [reply code/frontend/src/app/ui/number-input/number-input.component.ts]: Good catch — you're right, it's not needed. The signal update queues a change detection cycle which syncs the DOM input value. Removed.

File: code/frontend/src/app/ui/number-input/number-input.component.ts (hunk 1 above)
Comment (Flaminel) [reply code/frontend/src/app/ui/number-input/number-input.component.ts]: It's a nit pick, but they should have not stayed as inline code. It's fine this time tho. 😆

**Comment by Flaminel** [comment]
Thank you very much for your contribution!
